# Generated by Django 5.2 on 2026-01-18 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('machine_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mould',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('mould_code', models.CharField(max_length=50, unique=True)),
                ('total_cavity', models.PositiveIntegerField()),
                ('running_cavity', models.PositiveIntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.machine')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('part_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mould', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.mould')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=20)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.vendor')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
