# Generated by Django 5.2 on 2026-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_productconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
