# Generated by Django 5.2 on 2026-01-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
