# Generated by Django 5.2 on 2026-01-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_alter_salesinvoiceitem_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
