# Generated by Django 5.2 on 2026-03-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('same_state', models.BooleanField(default=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50)),
                ('total_quantity', models.FloatField()),
                ('total_weight', models.FloatField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.vendor')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.FloatField()),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.purchaseinvoice')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.rawmaterial')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
