# Generated by Django 5.2 on 2026-03-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('batch_name', models.CharField(max_length=100)),
                ('batch_weight_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('standard_output_qty', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='Masters.product')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('material_type', models.CharField(choices=[('RUBBER', 'Rubber'), ('METAL', 'Metal'), ('INSERT', 'Insert'), ('CHEMICAL', 'Chemical')], default='RUBBER', max_length=50)),
                ('quantity_kg_per_batch', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='Production.batchmaster')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.rawmaterial')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('production_date', models.DateField()),
                ('shift', models.CharField(choices=[('SHIFT-1', 'Shift 1'), ('SHIFT-2', 'Shift 2'), ('SHIFT-3', 'Shift 3')], max_length=20)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('running_cavity', models.PositiveIntegerField(blank=True, null=True)),
                ('batches_made', models.PositiveIntegerField(default=0)),
                ('finished_qty', models.PositiveIntegerField()),
                ('rejected_qty', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Production.batchmaster')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.machine')),
                ('mould', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.mould')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.product')),
            ],
            options={
                'ordering': ['-production_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRawMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('material_type', models.CharField(choices=[('RUBBER', 'Rubber'), ('METAL', 'Metal'), ('INSERT', 'Insert'), ('CHEMICAL', 'Chemical')], default='RUBBER', max_length=50)),
                ('quantity_consumed', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value_consumed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('production_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='Production.productionentry')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.rawmaterial')),
            ],
        ),
        migrations.AddIndex(
            model_name='productionentry',
            index=models.Index(fields=['product', 'machine'], name='Production__product_518b21_idx'),
        ),
        migrations.AddIndex(
            model_name='productionentry',
            index=models.Index(fields=['production_date'], name='Production__product_1662e8_idx'),
        ),
        migrations.AddIndex(
            model_name='productionrawmaterialconsumption',
            index=models.Index(fields=['production_entry'], name='Production__product_f6d8ab_idx'),
        ),
    ]
