# Generated by Django 5.2 on 2026-01-18 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0002_productconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('production_date', models.DateField()),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=20)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('planned_quantity', models.FloatField(default=0)),
                ('produced_quantity', models.FloatField()),
                ('rejected_quantity', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.machine')),
                ('mould', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.mould')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.product')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionRawMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('viewedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('quantity_consumed', models.FloatField()),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_consumed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('production_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.productionentry')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Masters.rawmaterial')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
