# Generated by Django 5.2 on 2026-03-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='production_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
